# Generated by Django 6.0.2 on 2026-04-03 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_theme_userappearance'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='themes/backgrounds/'),
        ),
    ]
