# Generated by Django 6.0.2 on 2026-08-04 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_activesession_loginactivity_notificationpreference_and_more'),
        ('ai', '0009_chatsession_is_deleted_chatsession_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='accent_color',
            field=models.CharField(blank=True, default='#a78bfa', max_length=30),
        ),
        migrations.AddField(
            model_name='theme',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='theme',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='themes/favicons/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='generated_colors',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='theme',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='is_global',
            field=models.BooleanField(default=False, help_text='True for core StudyHub platform themes'),
        ),
        migrations.AddField(
            model_name='theme',
            name='is_mandatory_schedule',
            field=models.BooleanField(default=False, help_text='If True, overrides user personal preference during active schedule window'),
        ),
        migrations.AddField(
            model_name='theme',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='themes/logos/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='mode',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('custom', 'Custom')], default='dark', max_length=20),
        ),
        migrations.AddField(
            model_name='theme',
            name='primary_color',
            field=models.CharField(blank=True, default='#6c63ff', max_length=30),
        ),
        migrations.AddField(
            model_name='theme',
            name='schedule_end',
            field=models.DateTimeField(blank=True, help_text='End time for scheduled activation', null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='schedule_start',
            field=models.DateTimeField(blank=True, help_text='Start time for scheduled activation', null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='secondary_color',
            field=models.CharField(blank=True, default='#3b82f6', max_length=30),
        ),
        migrations.AddField(
            model_name='theme',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='themes', to='ai.university'),
        ),
        migrations.AddField(
            model_name='userappearance',
            name='mode_preference',
            field=models.CharField(choices=[('system', 'System Default'), ('light', 'Light Mode'), ('dark', 'Dark Mode')], default='system', max_length=20),
        ),
        migrations.AlterField(
            model_name='theme',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='JSON object of CSS variables and values'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='theme_type',
            field=models.CharField(choices=[('builtin', 'Built-in'), ('university', 'University'), ('custom', 'Custom')], default='builtin', max_length=20),
        ),
        migrations.CreateModel(
            name='ThemeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('mode', models.CharField(default='dark', max_length=20)),
                ('primary_color', models.CharField(blank=True, max_length=30)),
                ('secondary_color', models.CharField(blank=True, max_length=30)),
                ('accent_color', models.CharField(blank=True, max_length=30)),
                ('generated_colors', models.JSONField(blank=True, default=dict)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='accounts.theme')),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('theme', 'version_number')},
            },
        ),
    ]
