"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", "dev-secret-key")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "True").lower() == "true"

ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'drf_yasg',
    'django_filters',
    'django_otp',
    'django_otp.plugins.otp_totp',

    'accounts',
    'courses',
    'assessments',
    'notifications',
    'focus',
    'ai',
    'gamification',

    "corsheaders"
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# CORS - Allow frontend to connect
CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'studyhub_db',
        'USER': 'postgres',
        'PASSWORD': 'Dev#18jk',
        'HOST': 'localhost',
        'PORT': '5432'
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Media files (uploaded course content: PDFs, videos, etc.)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

AUTH_USER_MODEL = 'accounts.User'

# ---------- Django REST Framework ----------
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,

    # ── No global throttling — each view applies its own throttle class ──
    'DEFAULT_THROTTLE_CLASSES': [],

    # ── AI-specific rate limits (change values here to adjust limits) ──
    'DEFAULT_THROTTLE_RATES': {
        'ai_daily': '50/day',    # Authenticated students: 50 messages/day
        'ai_burst': '5/min',     # Authenticated students: 5 messages/minute
        'ai_anon':  '5/day',     # Anonymous users: 5 messages/day
        'ai_admin': '100/day',   # Admin/superusers: 100 messages/day
    },

    # ── Custom exception handler for clean 429 JSON responses ──
    'EXCEPTION_HANDLER': 'config.exceptions.custom_exception_handler',
}

# ---------- Caching — Redis (used by throttling + general caching) ----------
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/1'),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'SOCKET_CONNECT_TIMEOUT': 5,   # seconds
            'SOCKET_TIMEOUT': 5,           # seconds
            'RETRY_ON_TIMEOUT': True,
            'MAX_CONNECTIONS': 1000,
            'IGNORE_EXCEPTIONS': True,     # fallback gracefully if Redis is down
        },
        'KEY_PREFIX': 'studyhub',
        'TIMEOUT': 86400,                  # default TTL: 24 hours
    }
}

# ---------- Account Recovery Security ----------
# Enforce strict throttling for recovery endpoints to prevent brute-force attacks
REST_FRAMEWORK['DEFAULT_THROTTLE_RATES'].update({
    'recovery_email': '3/hour',   # Max 3 emails per user/hour
    'recovery_ip': '5/hour',      # Max 5 attempts per IP/hour
    'recovery_global': '100/day', # Global circuit breaker
})

# ---------- 2FA / OTP Security ----------
REST_FRAMEWORK['DEFAULT_THROTTLE_RATES'].update({
    'otp_verify': '5/min',   # Max 5 OTP attempts per minute per IP
    'otp_setup':  '10/hour',   # Max 10 setup attempts per hour
})

# Temp token TTL for 2FA step-up (seconds)
TWO_FA_TEMP_TOKEN_TTL = 300  # 5 minutes

# ---------- Password Security ----------
PASSWORD_HISTORY_COUNT = 5
PASSWORD_RESET_TIMEOUT = 1800  # 30 minutes in seconds

# ---------- Email Configuration ----------
# Use console for local testing; Railway/Render will provide ENV vars for SMTP
if os.getenv('EMAIL_HOST'):
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.getenv('EMAIL_HOST')
    EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
    EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() == 'true'
    EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
    EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
    DEFAULT_FROM_EMAIL = f"StudyHub Security <{EMAIL_HOST_USER}>"
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    DEFAULT_FROM_EMAIL = "StudyHub Security <notifications@studyhub.edu>"

# ---------- Bot Protection (reCAPTCHA) ----------
RECAPTCHA_SECRET_KEY = os.getenv('RECAPTCHA_SECRET_KEY', '6LeIxAcTAAAAAGG-vFI1TnRWxMZNF6G4W_Noo7hx') # Test key
RECAPTCHA_MIN_SCORE = 0.5

# ---------- Production Security Settings ----------
# These will be enforced when deployed. For now, we prepare them.
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_SSL_REDIRECT = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000 # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# ---------- SimpleJWT ----------
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

CORS_ALLOW_ALL_ORIGINS = True

# ---------- RAG Debug Mode ----------
DEBUG_RAG = os.getenv('DEBUG_RAG', 'False').lower() in ('true', '1', 'yes')

# ---------- Logging ----------
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'ai': {
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG_RAG else 'INFO',
            'propagate': True,
        },
    },
}

# ---------- Swagger Settings ----------
SWAGGER_SETTINGS = {
    # Disable session-based auth in Swagger (we use JWT only)
    'USE_SESSION_AUTH': False,
    # Define JWT Bearer as the only auth scheme
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header',
            'description': 'Enter your JWT token as: **Bearer &lt;your_access_token&gt;**',
        }
    },
    # Apply Bearer security globally to all endpoints in Swagger
    'DEFAULT_AUTO_SCHEMA_CLASS': 'drf_yasg.inspectors.SwaggerAutoSchema',
    # Persist authorization across page refreshes
    'PERSIST_AUTH': True,
    'REFETCH_SCHEMA_WITH_AUTH': True,
    'REFETCH_SCHEMA_ON_LOGOUT': True,
}
