# Generated by Django 6.0.2 on 2026-04-06 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0007_topic_difficulty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FocusSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_goal', models.CharField(max_length=500)),
                ('mode', models.CharField(choices=[('normal', 'Normal Mode'), ('strict', 'Strict Mode')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('break', 'On Break'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='active', max_length=12)),
                ('suggested_focus_minutes', models.PositiveIntegerField(default=25)),
                ('selected_focus_minutes', models.PositiveIntegerField(default=25)),
                ('suggested_break_minutes', models.PositiveIntegerField(default=5)),
                ('selected_break_minutes', models.PositiveIntegerField(default=5)),
                ('suggestion_source', models.CharField(choices=[('difficulty', 'Topic Difficulty'), ('usage', 'Usage History'), ('hybrid', 'Hybrid'), ('manual', 'Manual Override')], default='difficulty', max_length=12)),
                ('total_focus_seconds', models.PositiveIntegerField(default=0)),
                ('total_break_seconds', models.PositiveIntegerField(default=0)),
                ('break_count', models.PositiveIntegerField(default=0)),
                ('interruption_count', models.PositiveIntegerField(default=0)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('break_started_at', models.DateTimeField(blank=True, null=True)),
                ('content_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='focus_sessions', to='courses.content')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='focus_sessions', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='focus_sessions', to='courses.subject')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='focus_sessions', to='courses.topic')),
            ],
            options={
                'verbose_name': 'Focus Session',
                'verbose_name_plural': 'Focus Sessions',
                'ordering': ['-start_time'],
            },
        ),
    ]
