# Generated by Django 6.0.2 on 2026-04-29 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_topic_difficulty'),
        ('focus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='focussession',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='focus_sessions', to='courses.course'),
        ),
    ]
