# Generated by Django 6.0.2 on 2026-08-24 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0003_add_soft_delete'),
        ('tasks', '0003_task_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='focussession',
            name='task',
            field=models.ForeignKey(blank=True, help_text='Optional: task being worked on during this session.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='focus_sessions', to='tasks.task'),
        ),
    ]
