# Generated by Django 6.0.2 on 2026-07-06 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='UTC datetime when this record was soft-deleted.', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='The user who soft-deleted this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='If True, this record has been soft-deleted and is hidden from normal queries.'),
        ),
    ]
