# Generated by Django 6.0.2 on 2026-03-22 10:27

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='course_files/', validators=[courses.models.validate_file_extension, courses.models.validate_file_size]),
        ),
    ]
