# Generated by Django 6.0.2 on 2026-04-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_content_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', help_text='Topic difficulty — used for focus timer suggestions', max_length=10),
        ),
    ]
