# Generated by Django 6.0.2 on 2026-05-11 (manually reordered for correctness)

import courses.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_coursecategory_course_duration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 1. Meta options
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['order', 'created_at']},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['order', 'created_at']},
        ),

        # 2. Remove old fields
        migrations.RemoveField(model_name='course', name='is_public'),
        migrations.RemoveField(model_name='course', name='name'),
        migrations.RemoveField(model_name='subject', name='name'),
        migrations.RemoveField(model_name='topic', name='name'),

        # 3. Add new fields to Course
        migrations.AddField(model_name='course', name='is_featured', field=models.BooleanField(default=False)),
        migrations.AddField(model_name='course', name='is_published', field=models.BooleanField(default=False)),
        migrations.AddField(model_name='course', name='slug', field=models.SlugField(blank=True, default='', max_length=220, unique=True)),
        migrations.AddField(model_name='course', name='title', field=models.CharField(default='', max_length=200)),
        migrations.AddField(model_name='course', name='updated_at', field=models.DateTimeField(auto_now=True)),
        migrations.AlterField(
            model_name='course', name='created_by',
            field=models.ForeignKey(limit_choices_to={'role': 'admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='courses_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(model_name='course', name='description', field=models.TextField(blank=True)),

        # 4. Add new fields to Subject (slug must come before unique_together)
        migrations.AddField(
            model_name='subject', name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(model_name='subject', name='is_published', field=models.BooleanField(default=True)),
        migrations.AddField(model_name='subject', name='order', field=models.PositiveIntegerField(default=0)),
        migrations.AddField(model_name='subject', name='slug', field=models.SlugField(blank=True, default='', max_length=220)),
        migrations.AddField(model_name='subject', name='thumbnail', field=models.ImageField(blank=True, null=True, upload_to='subject_thumbnails/')),
        migrations.AddField(model_name='subject', name='title', field=models.CharField(default='', max_length=200)),
        migrations.AddField(model_name='subject', name='updated_at', field=models.DateTimeField(auto_now=True)),

        # 5. Add new fields to Topic (slug must come before unique_together)
        migrations.AddField(
            model_name='topic', name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(model_name='topic', name='estimated_duration', field=models.CharField(blank=True, help_text='e.g. "2h 30m"', max_length=50)),
        migrations.AddField(model_name='topic', name='is_published', field=models.BooleanField(default=True)),
        migrations.AddField(model_name='topic', name='order', field=models.PositiveIntegerField(default=0)),
        migrations.AddField(model_name='topic', name='slug', field=models.SlugField(blank=True, default='', max_length=220)),
        migrations.AddField(model_name='topic', name='thumbnail', field=models.ImageField(blank=True, null=True, upload_to='topic_thumbnails/')),
        migrations.AddField(model_name='topic', name='title', field=models.CharField(default='', max_length=200)),
        migrations.AddField(model_name='topic', name='updated_at', field=models.DateTimeField(auto_now=True)),
        migrations.AlterField(
            model_name='topic', name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10),
        ),

        # 6. Now safe to apply unique_together (slug fields exist)
        migrations.AlterUniqueTogether(name='subject', unique_together={('course', 'slug')}),
        migrations.AlterUniqueTogether(name='topic', unique_together={('subject', 'slug')}),

        # 7. Create the new Material model
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('slug', models.SlugField(blank=True, default='', max_length=220)),
                ('description', models.TextField(blank=True)),
                ('material_type', models.CharField(
                    choices=[('video', 'Video'), ('pdf', 'PDF'), ('notes', 'Notes'), ('quiz', 'Quiz'), ('assignment', 'Assignment'), ('link', 'External Link')],
                    default='pdf', max_length=20,
                )),
                ('file', models.FileField(blank=True, null=True, upload_to='course_files/', validators=[courses.models.validate_file_extension, courses.models.validate_file_size])),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='material_thumbnails/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube / direct video URL')),
                ('external_url', models.URLField(blank=True, help_text='External resource URL')),
                ('text_content', models.TextField(blank=True, help_text='Rich text / notes content')),
                ('duration', models.CharField(blank=True, help_text='e.g. "45 min"', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_downloadable', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='courses.topic')),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'unique_together': {('topic', 'slug')},
            },
        ),
    ]
