# Generated by Django 6.0.2 on 2026-07-06 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_add_unique_enrollment_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='enrollment',
            name='unique_enrollment_per_user_course',
        ),
        migrations.AlterUniqueTogether(
            name='material',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='progress',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='content',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='UTC datetime when this record was soft-deleted.', null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='The user who soft-deleted this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='content',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='If True, this record has been soft-deleted and is hidden from normal queries.'),
        ),
        migrations.AddField(
            model_name='course',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='UTC datetime when this record was soft-deleted.', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='The user who soft-deleted this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='If True, this record has been soft-deleted and is hidden from normal queries.'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='UTC datetime when this record was soft-deleted.', null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='The user who soft-deleted this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='If True, this record has been soft-deleted and is hidden from normal queries.'),
        ),
        migrations.AddField(
            model_name='material',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='UTC datetime when this record was soft-deleted.', null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='The user who soft-deleted this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='material',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='If True, this record has been soft-deleted and is hidden from normal queries.'),
        ),
        migrations.AddField(
            model_name='progress',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='UTC datetime when this record was soft-deleted.', null=True),
        ),
        migrations.AddField(
            model_name='progress',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='The user who soft-deleted this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='progress',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='If True, this record has been soft-deleted and is hidden from normal queries.'),
        ),
        migrations.AddField(
            model_name='subject',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='UTC datetime when this record was soft-deleted.', null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='The user who soft-deleted this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='If True, this record has been soft-deleted and is hidden from normal queries.'),
        ),
        migrations.AddField(
            model_name='topic',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='UTC datetime when this record was soft-deleted.', null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='The user who soft-deleted this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topic',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='If True, this record has been soft-deleted and is hidden from normal queries.'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('student', 'course'), name='unique_enrollment_per_user_course_active'),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('topic', 'slug'), name='unique_material_topic_slug_active'),
        ),
        migrations.AddConstraint(
            model_name='progress',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('student', 'content'), name='unique_progress_student_content_active'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('course', 'slug'), name='unique_subject_course_slug_active'),
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('subject', 'slug'), name='unique_topic_subject_slug_active'),
        ),
    ]
