# Generated by Django 6.0.2 on 2026-04-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_chatmessage_chatattachment_chatsession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatattachment',
            name='flagged_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatattachment',
            name='is_approved_for_ai',
            field=models.BooleanField(default=False, help_text='Only true if moderation_status is approved'),
        ),
        migrations.AddField(
            model_name='chatattachment',
            name='moderation_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chatattachment',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'Pending Scan'), ('approved_academic', 'Approved (Academic)'), ('approved_medical', 'Approved (Medical)'), ('rejected_explicit', 'Rejected (Explicit/Unsafe)'), ('rejected_malware', 'Rejected (Malware)'), ('manual_review', 'Manual Review Required')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='studentnote',
            name='flagged_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentnote',
            name='is_approved_for_ai',
            field=models.BooleanField(default=False, help_text='Only true if moderation_status is approved'),
        ),
        migrations.AddField(
            model_name='studentnote',
            name='moderation_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentnote',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'Pending Scan'), ('approved_academic', 'Approved (Academic)'), ('approved_medical', 'Approved (Medical)'), ('rejected_explicit', 'Rejected (Explicit/Unsafe)'), ('rejected_malware', 'Rejected (Malware)'), ('manual_review', 'Manual Review Required')], default='pending', max_length=20),
        ),
    ]
