# Generated by Django 6.0.2 on 2026-04-29 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_chatattachment_flagged_reason_and_more'),
        ('courses', '0007_topic_difficulty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_snapshot', models.CharField(blank=True, default='', help_text='Role of user at request time. Preserved even if user record changes.', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='UTC timestamp of when the request was received.')),
                ('request_type', models.CharField(choices=[('chat', 'Chat'), ('summary', 'Summarisation'), ('quiz', 'Quiz Help'), ('explain', 'Explanation'), ('other', 'Other')], default='chat', max_length=20)),
                ('query_text', models.CharField(blank=True, default='', help_text='First 300 chars of the user query. Stored for admin diagnostics only.', max_length=300)),
                ('detected_topic', models.CharField(blank=True, default='', help_text='Topic string passed in the request (subject/topic field from chat).', max_length=200)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('throttled', 'Throttled'), ('blocked', 'Blocked by Moderation')], db_index=True, default='success', max_length=20)),
                ('response_time_ms', models.PositiveIntegerField(blank=True, help_text='Total round-trip time in milliseconds from request to response.', null=True)),
                ('error_code', models.CharField(blank=True, default='', help_text="Short error code if status is failed (e.g. 'gemini_timeout').", max_length=50)),
                ('input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('total_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('model_name', models.CharField(blank=True, default='', max_length=100)),
                ('is_archived', models.BooleanField(default=False, help_text='Set to True by the archive_ai_logs management command. Archived entries are excluded from live dashboards.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Flexible JSON store for future fields (e.g. RAG chunk count, focus session id).')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_request_logs', to='courses.course')),
                ('related_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_request_logs', to='courses.topic')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_request_logs', to='courses.subject')),
                ('user', models.ForeignKey(blank=True, help_text='The user who made the request (nullable to preserve stats after deletion).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_request_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Request Log',
                'verbose_name_plural': 'AI Request Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='ai_log_user_ts_idx'), models.Index(fields=['course', 'subject', 'related_topic'], name='ai_log_course_idx'), models.Index(fields=['timestamp', 'status'], name='ai_log_ts_status_idx'), models.Index(fields=['is_archived', 'timestamp'], name='ai_log_archive_idx')],
            },
        ),
    ]
