# Generated by Django 6.0.2 on 2026-07-26 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_airequestlog'),
        ('courses', '0011_add_soft_delete_to_courses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='airequestlog',
            name='endpoint',
            field=models.CharField(blank=True, default='', help_text='View name / URL pattern that handled this request.', max_length=100),
        ),
        migrations.AddField(
            model_name='airequestlog',
            name='provider',
            field=models.CharField(blank=True, default='google', help_text="AI provider used for this request (e.g. 'google').", max_length=50),
        ),
        migrations.AddField(
            model_name='airequestlog',
            name='retrieval_score',
            field=models.FloatField(blank=True, help_text='Top cosine similarity score from RAG retrieval (0.0–1.0).', null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='retrieval_confidence',
            field=models.FloatField(blank=True, help_text='Top cosine similarity from RAG retrieval for this AI response (0.0–1.0).', null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='is_summarized',
            field=models.BooleanField(default=False, help_text='True when older messages in this session have been summarised.'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='summarized_at',
            field=models.DateTimeField(blank=True, help_text='When the summary was last generated.', null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='summary_covers_up_to_message',
            field=models.IntegerField(blank=True, help_text='ID of the last ChatMessage included in summary_text.', null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='summary_text',
            field=models.TextField(blank=True, default='', help_text='Compressed summary of messages older than summary_covers_up_to_message.'),
        ),
        migrations.CreateModel(
            name='AIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assistant_name', models.CharField(default='StudyHub AI', help_text='Display name for the AI assistant on the teacher panel.', max_length=100)),
                ('provider', models.CharField(choices=[('google', 'Google Gemini')], default='google', max_length=50)),
                ('model_name', models.CharField(choices=[('gemini-2.0-flash', 'Gemini 2.0 Flash (Recommended)'), ('gemini-2.5-flash', 'Gemini 2.5 Flash'), ('gemini-flash-latest', 'Gemini Flash Latest')], default='gemini-2.0-flash', max_length=100)),
                ('teaching_style', models.CharField(choices=[('beginner_friendly', 'Beginner Friendly'), ('academic', 'Academic'), ('advanced', 'Advanced')], default='academic', max_length=30)),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('temperature', models.FloatField(default=0.3, help_text='Generation temperature (0.1 = focused, 1.0 = creative).')),
                ('custom_system_prompt', models.TextField(blank=True, default='', help_text='Optional extra system instruction prepended to every AI call for this teacher.')),
                ('enable_chat', models.BooleanField(default=True)),
                ('enable_question_generation', models.BooleanField(default=True)),
                ('enable_summarization', models.BooleanField(default=True)),
                ('enable_exam_mode', models.BooleanField(default=True)),
                ('enable_rag', models.BooleanField(default=True)),
                ('enable_external_knowledge', models.BooleanField(default=False, help_text='Allow AI to use knowledge outside uploaded documents. Off by default for safety.')),
                ('institution', models.CharField(blank=True, default='', help_text='Institution name. Will become a FK when multi-tenant Institution model is built.', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_subjects', models.ManyToManyField(blank=True, help_text='AI will only answer questions about these subjects (empty = all subjects allowed).', related_name='ai_configs_allowed', to='courses.subject')),
                ('blocked_topics', models.ManyToManyField(blank=True, help_text='AI will refuse to discuss these topics.', related_name='ai_configs_blocked', to='courses.topic')),
                ('teacher', models.OneToOneField(limit_choices_to={'role': 'admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='ai_configuration', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Configuration',
                'verbose_name_plural': 'AI Configurations',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(blank=True, default='', help_text='Institution name for future multi-tenant isolation.', max_length=200)),
                ('title', models.CharField(max_length=300)),
                ('file', models.FileField(upload_to='knowledge_docs/%Y/%m/')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF Document'), ('docx', 'Word Document (DOCX)'), ('txt', 'Plain Text')], default='txt', max_length=10)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes.')),
                ('extracted_text', models.TextField(blank=True, default='')),
                ('embedding_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='', help_text="Populated when embedding_status is 'failed'.")),
                ('total_chunks', models.IntegerField(default=0)),
                ('embedded_chunks', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_documents', to='courses.course')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_documents', to='courses.subject')),
                ('uploaded_by', models.ForeignKey(limit_choices_to={'role': 'admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Knowledge Document',
                'verbose_name_plural': 'Knowledge Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.IntegerField()),
                ('chunk_text', models.TextField()),
                ('token_count', models.IntegerField(default=0, help_text='Approximate token count (len(chunk_text) // 4).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='ai.knowledgedocument')),
            ],
            options={
                'verbose_name': 'Knowledge Chunk',
                'verbose_name_plural': 'Knowledge Chunks',
                'ordering': ['document', 'chunk_index'],
                'unique_together': {('document', 'chunk_index')},
            },
        ),
        migrations.CreateModel(
            name='KnowledgeEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding_vector', models.TextField(help_text='JSON-serialized list of floats.')),
                ('embedding_model', models.CharField(default='gemini-embedding-001', max_length=100)),
                ('embedding_version', models.CharField(default='v1', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chunk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='ai.knowledgechunk')),
            ],
            options={
                'verbose_name': 'Knowledge Embedding',
                'verbose_name_plural': 'Knowledge Embeddings',
            },
        ),
    ]
