# Generated by Django 6.0.2 on 2026-07-27 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0005_ai_teacher_panel_v2'),
        ('courses', '0011_add_soft_delete_to_courses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Archived conversations are hidden from the main list but not deleted.'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='is_shared',
            field=models.BooleanField(default=False, help_text='True when the conversation has been shared.'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='last_message_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the most recent message in this session.', null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='share_token',
            field=models.CharField(blank=True, help_text='Unique token for public/institution sharing link.', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='sharing_level',
            field=models.CharField(choices=[('private', 'Private'), ('institution', 'Shared within Institution'), ('public', 'Public Link')], default='private', help_text='Who can see this conversation when shared.', max_length=20),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='subject',
            field=models.ForeignKey(blank=True, help_text='Subject context for this conversation (teacher workspace).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to='courses.subject'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='topic',
            field=models.ForeignKey(blank=True, help_text='Topic context for this conversation (teacher workspace).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to='courses.topic'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='title',
            field=models.CharField(default='New Conversation', help_text='Auto-generated from the first question, or user-renamed', max_length=500),
        ),
        migrations.CreateModel(
            name='AIGeneratedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('notes', 'Study Notes'), ('quiz', 'Quiz'), ('flashcards', 'Flashcards'), ('assignment', 'Assignment'), ('lecture_material', 'Lecture Material'), ('blooms_questions', "Bloom's Taxonomy Questions")], max_length=30)),
                ('title', models.CharField(max_length=400)),
                ('content', models.TextField(help_text='Raw generated content (JSON or text).')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('reviewed', 'Reviewed'), ('published', 'Published')], default='draft', help_text="Never auto-publish. Teacher must explicitly change to 'reviewed' or 'published'.", max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Extra parameters (quiz type, difficulty, question count, etc.).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_generated_content', to='courses.course')),
                ('source_session', models.ForeignKey(blank=True, help_text='The conversation this content was generated from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_content', to='ai.chatsession')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_generated_content', to='courses.subject')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='generated_content', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_generated_content', to='courses.topic')),
            ],
            options={
                'verbose_name': 'AI Generated Content',
                'verbose_name_plural': 'AI Generated Content',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#6366f1', help_text='Hex color for the tag badge.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='conversation_tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversation Tag',
                'verbose_name_plural': 'Conversation Tags',
                'ordering': ['name'],
                'unique_together': {('teacher', 'name')},
            },
        ),
        migrations.AddField(
            model_name='chatsession',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='User-defined tags for organization.', related_name='sessions', to='ai.conversationtag'),
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('prompt', models.TextField(help_text='The reusable prompt text.')),
                ('category', models.CharField(choices=[('notes', 'Generate Notes'), ('quiz', 'Create Quiz'), ('assignment', 'Create Assignment'), ('explain', 'Explain Topic'), ('case_study', 'Create Case Study'), ('custom', 'Custom')], default='custom', max_length=30)),
                ('is_global', models.BooleanField(default=False, help_text='If True, visible to all teachers in the institution.')),
                ('use_count', models.PositiveIntegerField(default=0, help_text='How many times this template has been used.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='prompt_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prompt Template',
                'verbose_name_plural': 'Prompt Templates',
                'ordering': ['-use_count', '-created_at'],
            },
        ),
    ]
