# Generated by Django 6.0.2 on 2026-08-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0007_aiquotapolicy_university_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconfiguration',
            name='allow_global_knowledge',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aiconfiguration',
            name='knowledge_priority',
            field=models.CharField(choices=[('material_only', 'Material Only'), ('material_first', 'University Material First + Global Knowledge'), ('global_first', 'Global Knowledge Enabled')], default='material_first', max_length=20),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='enable_voice',
            field=models.BooleanField(default=False),
        ),
    ]
