# Generated by Django 6.0.2 on 2026-08-03 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0008_aiconfiguration_allow_global_knowledge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='university',
            field=models.ForeignKey(blank=True, help_text='University ownership for tenant isolation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to='ai.university'),
        ),
    ]
