# Generated by Django 6.0.2 on 2026-04-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userbadge',
            options={'ordering': ['-last_earned_at']},
        ),
        migrations.AddField(
            model_name='badge',
            name='milestone_value',
            field=models.IntegerField(default=0, help_text='Threshold count for tiered badges'),
        ),
        migrations.AddField(
            model_name='badge',
            name='repeatable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='badge',
            name='tier',
            field=models.CharField(choices=[('none', 'No Tier'), ('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('legendary', 'Legendary')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='userbadge',
            name='earned_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userbadge',
            name='last_earned_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
