# Generated by Django 6.0.2 on 2026-08-20 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_alter_userbadge_options_badge_milestone_value_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(unique=True)),
                ('xp_threshold', models.IntegerField()),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['level'],
            },
        ),
        migrations.AddField(
            model_name='badge',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='AchievementAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('badge_created', 'Badge Created'), ('badge_updated', 'Badge Updated'), ('rule_modified', 'Rule Modified'), ('manual_award', 'Manual Award'), ('manual_revoke', 'Manual Revoke'), ('xp_modified', 'XP Modified'), ('status_change', 'Status Changed')], max_length=50)),
                ('reason', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievement_actions_performed', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievement_actions_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AchievementRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=50)),
                ('operator', models.CharField(choices=[('>=', 'Greater than or equal'), ('>', 'Greater than'), ('==', 'Equal to'), ('<=', 'Less than or equal'), ('<', 'Less than')], default='>=', max_length=5)),
                ('value', models.FloatField()),
                ('required_occurrences', models.IntegerField(default=1, help_text='Number of times this rule must be met')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='gamification.badge')),
            ],
        ),
        migrations.CreateModel(
            name='XPTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('reason', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
