# Generated by Django 6.0.2 on 2026-04-16 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('material_type', models.CharField(choices=[('pdf', 'PDF'), ('doc', 'Document'), ('ppt', 'Presentation'), ('image', 'Image'), ('text', 'Text Note'), ('link', 'External Link')], max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='student_materials/')),
                ('external_url', models.URLField(blank=True, null=True)),
                ('note_text', models.TextField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('topic', models.CharField(blank=True, max_length=255)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('shared', 'Shared')], default='private', max_length=10)),
                ('folder_name', models.CharField(blank=True, max_length=255)),
                ('favorite', models.BooleanField(default=False)),
                ('ai_indexed', models.BooleanField(default=False)),
                ('source', models.CharField(default='student_upload', max_length=50)),
                ('is_deleted', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialUserNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_content', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_notes', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notes', to='materials.studentmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=True)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_comment', models.BooleanField(default=True)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_access', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='materials.studentmaterial')),
            ],
            options={
                'ordering': ['-granted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='studentmaterial',
            index=models.Index(fields=['student', 'is_deleted'], name='materials_s_student_bbe216_idx'),
        ),
        migrations.AddIndex(
            model_name='studentmaterial',
            index=models.Index(fields=['student', 'favorite'], name='materials_s_student_313cd5_idx'),
        ),
        migrations.AddIndex(
            model_name='studentmaterial',
            index=models.Index(fields=['student', 'folder_name'], name='materials_s_student_6a0af5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='materialusernote',
            unique_together={('material', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='materialaccess',
            unique_together={('material', 'user')},
        ),
    ]
