# Generated by Django 6.0.2 on 2026-04-23 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_materialcomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmaterial',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentmaterial',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_materials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='studentmaterial',
            index=models.Index(fields=['student', 'is_deleted', 'deleted_at'], name='materials_s_student_fb27d0_idx'),
        ),
    ]
