# Generated by Django 6.0.2 on 2026-07-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_add_deleted_at_deleted_by_to_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmaterial',
            name='material_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('doc', 'Word file'), ('ppt', 'PPT'), ('excel', 'Excel/CSV'), ('image', 'Image'), ('text', 'Text Note'), ('link', 'External Link')], max_length=20),
        ),
    ]
